"""Advanced RAG pipeline using LangGraph.

Workflow:
  START
    - transform_query   (HyDE: формирует гипотетический ответ на запрос)
    - retrieve          (Hybrid BM25 + FAISS MMR via RRF)
    - rerank            (LLM оценивает документы по шкале 1-10, оставляет топ-5)
    - generate          (Добавляет обязательную ссылку [Статья N])
    - check_consistency (Проверка утверждений на соответствие контексту, возвращает JSON)
    - finalize          (Форматирует список источников, составляет окончательное сообщение)
  END
"""

import json
import re
from typing import Annotated, List

from langchain_core.documents import Document
from langchain_core.messages import AIMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.checkpoint.memory import MemorySaver
from langgraph.constants import END
from langgraph.graph import START, StateGraph, add_messages
from typing_extensions import TypedDict

from .llms import chat_model
from .retriever import hybrid_retrieve, ARTICLES_BY_NUMBER

# Статья 1 всегда включается в контекст целиком (содержит все базовые определения)
_ARTICLE_1: Document | None = ARTICLES_BY_NUMBER.get("1")


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------
class State(TypedDict):
    question: str
    hyde_document: str  # Hypothetical passage generated by HyDE
    context: List[Document]  # Retrieved + reranked documents
    answer: str  # Generated answer with inline [Статья N] citations
    sources: List[dict]  # [{article, title, excerpt}]
    consistency: dict  # {verified, unverified, score}
    messages: Annotated[list, add_messages]


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------
HYDE_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "Ты эксперт по российскому градостроительному законодательству. "
            "Напиши гипотетический фрагмент текста из Градостроительного кодекса РФ, "
            "который мог бы отвечать на следующий вопрос. "
            "Фрагмент должен быть написан в стиле официального юридического текста "
            "и ссылаться на конкретные нормы и термины. "
            "Объём: 4-6 предложения. Пиши только текст фрагмента, без пояснений.",
        ),
        ("human", "{question}"),
    ]
)

GENERATE_SYSTEM = """\
Ты — юридический ассистент по Градостроительному кодексу Российской Федерации.

Твоя задача — дать точный, структурированный ответ на вопрос пользователя, \
основываясь исключительно на предоставленных фрагментах кодекса.

ВАЖНО — приоритет источников:
Статья 1 содержит официальные определения понятий и имеет ПЕРВОСТЕПЕННОЕ значение. \
Если любой другой фрагмент противоречит определениям или нормам Статьи 1, \
безоговорочно следуй Статье 1 и явно укажи на это противоречие в ответе.

Правила:
1. Цитируй каждое утверждение с указанием источника в формате [Статья N], \
   где N — номер статьи. Пример: «Застройщик вправе передать свои функции [Статья 1].»
2. Если фрагменты не содержат ответа на вопрос, прямо скажи об этом.
3. Отвечай на русском языке, юридически точно и структурированно.
4. Не придумывай информацию, которой нет в предоставленных фрагментах.
5. Если во фрагментах присутствуют таблицы (markdown-таблицы с разделителем |), \
   воспроизведи их в ответе в формате markdown, сохраняя все строки и столбцы. \
   Не заменяй таблицы текстовым пересказом.

Фрагменты кодекса:
{context}
"""

GENERATE_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system", GENERATE_SYSTEM),
        ("human", "{question}"),
    ]
)

RERANK_TEMPLATE = """\
Оцени, насколько следующий фрагмент из Градостроительного кодекса РФ \
релевантен вопросу пользователя. Ответь только числом от 1 до 10, \
где 10 — максимальная релевантность, 1 — полная нерелевантность.

Вопрос: {question}

Фрагмент (Статья {article}):
{content}

Оценка (только цифра):"""

CONSISTENCY_TEMPLATE = """\
Ты — проверяющий редактор. Сравни ответ ассистента с исходными фрагментами \
Градостроительного кодекса РФ.

Вопрос: {question}

Ответ ассистента:
{answer}

Исходные фрагменты кодекса:
{context}

ВАЖНО: Статья 1 является первостепенным источником определений и норм. \
Любое утверждение, противоречащее Статье 1, считается неверифицированным \
независимо от того, встречается ли оно в других статьях.

Задача: выясни, какие утверждения из ответа подтверждаются фрагментами, \
а какие нет (или сформулированы неточно). Отдельно отметь любые противоречия \
со Статьёй 1 в списке unverified.

Верни строго валидный JSON без каких-либо пояснений:
{{
  "verified": ["утверждение 1", "утверждение 2"],
  "unverified": ["утверждение X"],
  "score": 0.95
}}

Где "score" — доля верифицированных утверждений (0.0–1.0).
JSON:"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _smart_truncate(text: str, max_chars: int) -> str:
    """Truncate text at paragraph boundary so markdown tables are never split."""
    if len(text) <= max_chars:
        return text
    paragraphs = text.split("\n\n")
    result, total = [], 0
    for p in paragraphs:
        chunk_len = len(p) + 2  # +2 for the \n\n separator
        if total + chunk_len > max_chars:
            break
        result.append(p)
        total += chunk_len
    return "\n\n".join(result) if result else text[:max_chars]


def _extract_article_number(doc: Document) -> str:
    """Extract article number from metadata, e.g. 'Статья 42. Заголовок' → '42'."""
    raw = doc.metadata.get("Статья", "")
    match = re.search(r"(\d+[\.\d]*)", raw)
    return match.group(1).rstrip(".") if match else "?"


def _format_context_for_prompt(docs: List[Document]) -> str:
    """Format documents with article numbers for LLM prompts.

    Статья 1 включается целиком (без усечения) — она содержит все базовые
    определения и должна передаваться модели без каких-либо изменений.
    """
    parts = []
    for doc in docs:
        article_num = _extract_article_number(doc)
        content = (
            doc.page_content
            if article_num == "1"
            else _smart_truncate(doc.page_content, 8000)
        )
        parts.append(f"[Статья {article_num}]\n{content}")
    return "\n\n---\n\n".join(parts)


# ---------------------------------------------------------------------------
# Node 1: transform_query (HyDE)
# ---------------------------------------------------------------------------
def transform_query(state: State) -> dict:
    """Generate a hypothetical codex passage using HyDE technique."""
    question = state["messages"][-1].content
    response = chat_model.invoke(HYDE_PROMPT.format_messages(question=question))
    return {
        "question": question,
        "hyde_document": response.content,
    }


# ---------------------------------------------------------------------------
# Node 2: retrieve (Hybrid BM25 + FAISS MMR)
# ---------------------------------------------------------------------------
def retrieve(state: State) -> dict:
    """Run hybrid retrieval using the HyDE document as the search query.

    Статья 1 всегда добавляется в начало контекста, если её нет среди
    результатов поиска.
    """
    hyde_doc = state.get("hyde_document") or state["question"]
    docs = hybrid_retrieve(hyde_doc, k_final=10)

    if _ARTICLE_1 is not None:
        already_present = any(_extract_article_number(d) == "1" for d in docs)
        if not already_present:
            docs = [_ARTICLE_1] + docs

    return {"context": docs}


# ---------------------------------------------------------------------------
# Node 3: rerank (LLM-based scoring)
# ---------------------------------------------------------------------------
def rerank(state: State) -> dict:
    """Score each retrieved document 1-10 for relevance, keep top 5.

    Статья 1 исключается из ранжирования и всегда сохраняется в начале контекста.
    """
    question = state["question"]
    docs = state["context"]

    # Отделяем Статью 1 — она не участвует в ранжировании
    pinned = [d for d in docs if _extract_article_number(d) == "1"]
    to_rank = [d for d in docs if _extract_article_number(d) != "1"]

    scored: list[tuple[float, Document]] = []
    for doc in to_rank:
        article_num = _extract_article_number(doc)
        prompt_text = RERANK_TEMPLATE.format(
            question=question,
            article=article_num,
            content=_smart_truncate(doc.page_content, 2000),
        )
        response = chat_model.invoke([{"role": "user", "content": prompt_text}])
        raw = response.content.strip()
        match = re.search(r"(\d+)", raw)
        score = float(match.group(1)) if match else 5.0
        scored.append((score, doc))

    scored.sort(key=lambda x: x[0], reverse=True)
    top_docs = pinned + [doc for _, doc in scored[:5]]
    return {"context": top_docs}


# ---------------------------------------------------------------------------
# Node 4: generate
# ---------------------------------------------------------------------------
def generate(state: State) -> dict:
    """Generate answer with inline [Статья N] citations.
    Содержание Статьи 1 важнее остальных, если что-то противречит — ориентируйся на неё.
    """
    context_str = _format_context_for_prompt(state["context"])
    messages = GENERATE_PROMPT.format_messages(
        question=state["question"],
        context=context_str,
    )
    response = chat_model.invoke(messages)
    return {"answer": response.content}


# ---------------------------------------------------------------------------
# Node 5: check_consistency (Self-consistency checking)
# ---------------------------------------------------------------------------
def check_consistency(state: State) -> dict:
    """Verify answer claims against retrieved context."""
    context_str = _format_context_for_prompt(state["context"])
    prompt_text = CONSISTENCY_TEMPLATE.format(
        question=state["question"],
        answer=state["answer"],
        context=context_str,
    )
    response = chat_model.invoke([{"role": "user", "content": prompt_text}])

    raw = response.content.strip()
    # Strip markdown code fences if present
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.MULTILINE)
    raw = re.sub(r"\s*```$", "", raw, flags=re.MULTILINE)

    try:
        consistency = json.loads(raw)
    except json.JSONDecodeError:
        consistency = {
            "verified": [],
            "unverified": [],
            "score": 0.5,
        }
    return {"consistency": consistency}


# ---------------------------------------------------------------------------
# Node 6: finalize (Source Attribution)
# ---------------------------------------------------------------------------
def finalize(state: State) -> dict:
    """Build structured sources list and compose final response message."""
    sources = []
    seen_articles = set()

    for doc in state["context"]:
        article_num = _extract_article_number(doc)
        if article_num in seen_articles:
            continue
        seen_articles.add(article_num)

        raw_title = doc.metadata.get("Статья", f"Статья {article_num}")
        
        lines = doc.page_content.split("\n")
        body_lines = [l for l in lines if not l.strip().startswith("#")]
        excerpt = " ".join(body_lines).strip()[:300]

        sources.append(
            {
                "article": article_num,
                "title": raw_title,
                "excerpt": excerpt,
            }
        )

    sources.sort(key=lambda s: int(s["article"]) if s["article"].isdigit() else 999)

    final_text = state["answer"]
    consistency_score = state.get("consistency", {}).get("score", 1.0)


    if consistency_score < 0.8:
        unverified = state.get("consistency", {}).get("unverified", [])
        if unverified:
            final_text += (
                "\n\n---\n*Примечание: часть утверждений не нашла прямого "
                "подтверждения в тексте кодекса. Рекомендуется проверить.*"
            )

    return {
        "sources": sources,
        "messages": [AIMessage(content=final_text)],
    }


# ---------------------------------------------------------------------------
# Build and compile the graph
# ---------------------------------------------------------------------------
graph_builder = StateGraph(State)

graph_builder.add_node("transform_query", transform_query)
graph_builder.add_node("retrieve", retrieve)
graph_builder.add_node("rerank", rerank)
graph_builder.add_node("generate", generate)
graph_builder.add_node("check_consistency", check_consistency)
graph_builder.add_node("finalize", finalize)

graph_builder.add_edge(START, "transform_query")
graph_builder.add_edge("transform_query", "retrieve")
graph_builder.add_edge("retrieve", "rerank")
graph_builder.add_edge("rerank", "generate")
graph_builder.add_edge("generate", "check_consistency")
graph_builder.add_edge("check_consistency", "finalize")
graph_builder.add_edge("finalize", END)

memory = MemorySaver()
graph = graph_builder.compile(checkpointer=memory)
config = {"configurable": {"thread_id": "default"}}